version: "3"
services:

    mongo:
      container_name: mongo-container
      image: mongo:3
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - .\data:/data/db
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: example
 
        
    api:
      container_name: api-container
      build: .
      image: clean-node-api
      restart: always
      command: npm start
      environment:
        - MONGO_URL=mongodb://mongo:27017/clean-node-api
      volumes:
        - ./dist:/usr/src/clean-node-api/dist
      ports:
        - "5050:5050"
      links:
        - mongo